"""add exam_position and difficulty_level to tasks

Revision ID: 4787e938e827
Revises: e65a4369cdf8
Create Date: 2026-07-04 09:44:41.596062
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4787e938e827'
down_revision: Union[str, None] = 'e65a4369cdf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('exam_position', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('difficulty_level', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'difficulty_level')
    op.drop_column('tasks', 'exam_position')
    # ### end Alembic commands ###
